baseURL = 'https://madras-medley.netlify.app/'
languageCode = 'en-us'
title = 'Madras Medley'
theme = 'hugo-ink'
paginate = 5
copyright = "© Copyright notice"


[params]
   subtitle = "धर्मो रक्षति रक्षितः | Books | History | Travel | Technology | Civilization"
   mode = "auto"
   #avatar = "https://i.postimg.cc/MHZp8KTK/caricature.jpgG"
   mainSections = ['posts', 'book-reviews', 'thoughts', 'travel', 'published-articles' ]
   customCSS = "css/custom.css"  # Custom CSS applied to default styles.
   disqusShortname = ""


# Nav.   

[permalinks]
about = "/about/"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Book Reviews"
url = "/book-reviews"
weight = 2

[[menu.main]]
name = "Divya Desams"
url = "/divya-desams"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4


[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/abhidesikan"
